Don't try to be too clever, just prompt for installation

diff --git a/bin/preinstall b/bin/preinstall
--- a/bin/preinstall
+++ b/bin/preinstall
@@ -2,47 +2,33 @@
 
 NODE_MODULES_PATH="/usr/local/lib/node_modules"
 
-echo "AppGyver Steroids"
+echo "AppGyver Steroids\n"
 
 LOGGED_IN_USERNAME=$(logname)
-
-CHOWN_NODE_MODULES_CMD="sudo chown -R "$LOGGED_IN_USERNAME" /usr/local/lib/node_modules"
+CHOWN_NODE_MODULES_CMD="sudo chown -R $LOGGED_IN_USERNAME $NODE_MODULES_PATH"
 
 NODE_OWNED_BY=$(stat -f "%Su" $NODE_MODULES_PATH)
 
 if [ "$LOGGED_IN_USERNAME" != "$NODE_OWNED_BY" ]; then
-  echo "WARNING: $NODE_MODULES_PATH is owned by '$NODE_OWNED_BY' and not by '$LOGGED_IN_USERNAME'"
+  echo "ERROR: $NODE_MODULES_PATH is owned by '$NODE_OWNED_BY' and not by '$LOGGED_IN_USERNAME'"
   echo
-  echo "We recommend that you change the owner to '$LOGGED_IN_USERNAME' so that node NPM packages can be installed globally without sudo."
+  echo "Change user to '$LOGGED_IN_USERNAME' so that node NPM packages can be installed globally without sudo."
   echo
   echo "You can do this by:"
-  echo "  sudo chown -R $LOGGED_IN_USERNAME /usr/local/lib/node_modules"
+  echo "  sudo chown -R $LOGGED_IN_USERNAME $NODE_MODULES_PATH"
   echo
-  echo "Do you want us to do this now? (yes/no)"
-  read SHALL_WE_DO_IT
+  echo "Hit [enter] to do this now (ignore the few errors below and run this installer again)."
+  read
 
-  if [ "$SHALL_WE_DO_IT" == "yes" ] || [ "$SHALL_WE_DO_IT" == "y" ]; then
-    echo
-    echo "OK, doing it, we this might ask your password."
+  exit 1
 
-    $CHOWN_NODE_MODULES_CMD
-    echo "\ndone."
-  else
-    echo "\nNot doing it, you can do it later."
-    sleep 1
-  fi
-
-  echo "\n\nContinuing with the install.\n\n"
-  sleep 1
 fi
 
+echo "$NODE_MODULES_PATH is owned by $LOGGED_IN_USERNAME, good.\n"
 
+echo "Checking for required components ...\n"
 
-
-
-echo "checking for required components ...\n"
-
-REQUIRED_CMDS="git"
+REQUIRED_CMDS="gcc git"
 
 ERRORS=false
 for REQUIRED_CMD in $REQUIRED_CMDS
@@ -54,8 +40,10 @@ do
 done
 
 if [ "$ERRORS" == true ]; then
+  echo "\nInstall 'Command Line Tools for Xcode' see http://connect.apple.com.  Requires a free Apple ID."
   echo "\nWe recommend using homebrew to install git, see http://mxcl.github.com/homebrew/"
-  echo "\n\nHit [enter] to continue and install the dependencies.  Then run the installation again."
+
+  echo "\n\nHit [enter] to quit and install the dependencies.  Then run the installation again."
   read
   exit 1
 fi
