prevent installation as root

diff --git a/bin/preinstall b/bin/preinstall
--- a/bin/preinstall
+++ b/bin/preinstall
@@ -4,6 +4,19 @@ NODE_MODULES_PATH="/usr/local/lib/node_modules"
 
 echo "AppGyver Steroids\n"
 
+if [ "$USER" == "root" ]; then
+  echo "ERROR: do NOT run this as root (or use sudo)"
+  echo
+  echo "Hit [enter] and re-run installation:"
+  echo
+  echo "  npm install -g steroids"
+
+  read
+
+  exit 1
+fi
+
+
 LOGGED_IN_USERNAME=$(logname)
 CHOWN_NODE_MODULES_CMD="sudo chown -R $LOGGED_IN_USERNAME $NODE_MODULES_PATH"
 
